name: brm_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pip
  - pip:
    - anndata==0.11.4
    - scanpy==1.11.3
    - gseapy==1.1.9
    - lifelines==0.30.0
    - statsmodels==0.14.5
    - umap-learn==0.5.9.post2
    - harmonypy==0.0.10
    - torch==2.7.1
    - h5py==3.14.0
    - tqdm==4.67.1 